### PR TITLE
Added SRA processing to variation app.

### PR DESCRIPTION
**Pull request by JacobPorter**
Added SRA processing to variation service.

Fixed rast_export_genome from seeing gbk file.

Restored original run_var_annotate.

Removed whitespace.

Enhanced print out statements.

### CODE REVIEW

**Comment by JacobPorter** [comment]
This enhances the variation app to download and process fastq files from SRA accessions.  It uses the p3-sra command.  The p3-gto command replaced the p3-extract-gto command.

**Comment by olsonanl** [comment]
I merged, but missed noting originally that we are currently using the dev-slurm branch for the active app service. So if you could submit a PR against that branch that’d be cool.

**Comment by JacobPorter** [comment]
I did a pull request to dev-slurm.  There are conflicts with P3DataAPI.
________________________________

**Comment by olsonanl** [comment]
if you can try to do a pull against that branch in your code to resolve the conflicts and submit a corrected PR that'd be good

**Pull request merged**
