### PR TITLE
rastk advance parameters

### PR DESCRIPTION
**Pull request by aswarren**
A pull request to Bob's repo used to feed dev.

Potentially an issue:
Currently objects in the "custom_pipeline" group don't have individual enabled parameters
https://github.com/aswarren/app_service/blob/master/app_specs/GenomeAnnotation.json#L113

They simply rely on presence as their enabled state.

### CODE REVIEW

**Comment by olsonanl** [comment]
I'm curious how you view the role of the app spec these days - are you using this data to aid in populating the interface? (If you are using it to populate the set of possible stages in the pipeline that would be good; I will then use the spec as the master list for the P3 service or have it derived from a separate document that is the master list).

I'm asking also because the interface for annotating genomes from genbank has different inputs. It has a genbank file instead of the contigs, but also does not require the name / tax id / genetic code / domain fields since those come from the genbank file itself.

I see you're using a grouping syntax; did we strictly define that somewhere? One way to handle this is with a pair of mutually exclusive groups, one with the input options for contig upload, one with options for gb files.

I'll go ahead and merge this so we're both looking at the same starting point.

**Comment by olsonanl** [comment]
In addition, what should I expect in the incoming parameters to the service when a group is used? I see you also have nested groups.

**Comment by aswarren** [comment]
Really I just thought the app spec was something required from your side. Though at least I figured it as a way to communicate the potential JSON structure that will come out of the app interface. Indeed my plan was to use it to base the population of the interface on.
Are we expanding to use the genbank file as part of the annotation enhancement? I would say initially we can leave the extra options in there even if genbank is used. Though if you feel strongly we can make the spec changes to make a toggle, drop those interface elements. I guess in that case the annotation process would populate that same metadata for the workspace (taxid, genetic code, domain)? 
The grouping syntax I lifted from the assembly spec and was just a method for creating tuples of things that went together. :)

**Comment by olsonanl** [comment]
If we can use the spec as a contract between the frontend and back end that would be good even if it isn't machine validated. 

The group syntax seems fine - I just don't know what I should expect in the data when I see the groups.

It also might be useful to keep the specs as the contract so that we can build a testing / debugging environment that makes generic interfaces from the spec.

**Pull request merged**
