### PR TITLE
Added SRA processing to variation app.

### PR DESCRIPTION
**Pull request by JacobPorter**

### CODE REVIEW

**Comment by olsonanl** [comment]
take a look - there are some conflicts here. In particular there is a P3DataAPI call that is already in place to replace the use of p3-export-gto.

**Comment by JacobPorter** [comment]
I will test my code with the P3DataAPI.
________________________________

**Comment by olsonanl** [comment]
Poke me again when you fix the fatal error issue with missing SRA data

**Comment by JacobPorter** [comment]
I used die with the message instead of an exit statement. So, I think it can be merged now.

**Pull request merged**
