### PR TITLE
add RNA-rocket recipe

### PR DESCRIPTION
**Pull request by levinas**
Please copy all the files in `~fangfang/programs/binaries/` to the runtime. These include bowtie2, samtools and cufflinks that are required to run Andrew's RNA-Rocket recipe.

### CODE REVIEW

**Comment by olsonanl** [comment]
I would prefer to have recipes in the bootstrap building repo to build these dependencies instead of having them copied; we already had bowtie and samtools there so I have built those. Cufflinks is not there yet but we should add it; I will copy the cuff* tools over for now but I view that as a temporary solution.

Do gffread and gtf_to_sam come from cufflinks or elsewhere, or are those not deps for this code?

**Comment by levinas** [comment]
Bob, where is the bootstrap code? I can add the installation commands. We need to install Rockhopper (jar) and Andrew's Prok-tuxedo (python) installed properly, too; is bootstrap the way to do that?

**Comment by levinas** [comment]
And gffread and gtf_to_sam do come from cufflinks. I don't see the explicit invocation of these commands, but they might be needed.

**Comment by olsonanl** [comment]
It’s in the boostrap repo at https://github.com/olsonanl/bootstrap (currently a fork of the KBase bootstrap; we should probably move that over to the PATRIC3 org at some point).

Yes, adding those to the bootstrap would be the right mechanism. Tom has some examples I think of how he’s wrapped java apps.

—bob

On Jun 9, 2015, at 12:11 PM, Fangfang Xia <notifications@github.com<mailto:notifications@github.com>> wrote:


Bob, where is the bootstrap code? I can add the installation commands. We need to install Rockhopper (jar) and Andrew's Prok-tuxedo (python) installed properly, too; is bootstrap the way to do that?

**Pull request merged**
